/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#0e150e',
        surface: '#0e150e',
        'surface-dim': '#0e150e',
        'surface-bright': '#333b33',
        'surface-container-lowest': '#091009',
        'surface-container-low': '#161d16',
        'surface-container': '#1a221a',
        'surface-container-high': '#242c24',
        'surface-container-highest': '#2f372e',
        'surface-variant': '#2f372e',
        'surface-tint': '#4ae176',
        'on-background': '#dce5d9',
        'on-surface': '#dce5d9',
        'on-surface-variant': '#bccbb9',
        outline: '#869585',
        'outline-variant': '#3d4a3d',
        'inverse-surface': '#dce5d9',
        'inverse-on-surface': '#2a322a',

        primary: '#4be277',
        'on-primary': '#003915',
        'primary-container': '#22c55e',
        'on-primary-container': '#004b1e',
        'primary-fixed': '#6bff8f',
        'primary-fixed-dim': '#4ae176',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005321',
        'inverse-primary': '#006e2f',

        secondary: '#b9c7e0',
        'on-secondary': '#233144',
        'secondary-container': '#3c4a5e',
        'on-secondary-container': '#abb9d2',
        'secondary-fixed': '#d5e3fd',
        'secondary-fixed-dim': '#b9c7e0',
        'on-secondary-fixed': '#0d1c2f',
        'on-secondary-fixed-variant': '#3a485c',

        tertiary: '#ffb5ab',
        'on-tertiary': '#60130d',
        'tertiary-container': '#ff8b7c',
        'on-tertiary-container': '#76231b',
        'tertiary-fixed': '#ffdad5',
        'tertiary-fixed-dim': '#ffb4a9',
        'on-tertiary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#7f2a21',

        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        'gutter-mobile': '12px',
        md: '16px',
        'margin-mobile': '16px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'body-sm': ['Inter'],
        'body-lg': ['Inter'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
